DROP TABLE IF EXISTS customer_rewards_entity;

CREATE TABLE customer_rewards_entity (id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                        customer_identifier VARCHAR(50) NOT NULL,
                                        customer_points INTEGER NOT NULL, PRIMARY KEY (id));
ALTER TABLE customer_rewards_entity ADD CONSTRAINT customer_identifier_unique UNIQUE (customer_identifier);