# Data containers
services:
  h2:
    image: oscarfonts/h2
    container_name: h2-springnative
    environment:
       - H2_OPTIONS=-ifNotExists
    ports:
     - 1521:1521
     - 81:81
    networks:
      - custom
    volumes:
     - ./..:/opt/h2-data
  wiremock:
      image:  wiremock/wiremock:2.33.2
      container_name: wiremock-springnative
#      build: &build-dev
#        dockerfile: ./../wiremock/Dockerfile
#        tags:
#          - quarkus-demo/wiremock:latest
      command: --port 9999 --global-response-templating
      volumes:
        - ./../wiremock/mappings:/home/wiremock/mappings
        - ./../wiremock/__files:/home/wiremock/__files
      ports:
        - 9999:9999
      networks:
        - custom
  demo:
    image: discount-api-springnative:1.0.0-SNAPSHOT
    container_name: demo-springnative
    environment:
      - DATABASE_URL=jdbc:h2:tcp://h2:1521/~./test
      - WIREMOCK_URL=http://wiremock:9999
      - SPRING_PROFILES_ACTIVE=native
    ports:
       - 8080:8080
    links:
      - h2:h2
      - wiremock:wiremock
    networks:
      - custom
    depends_on:
      - h2

networks:

  custom:
    driver: bridge

